# GeoSite 标签: apple, cn, geolocation-!cn, disney, netflix, hulu
# GeoIP 标签: cn
api:
  http: '0.0.0.0:9092'
include: []
log:
  file: /var/log/mosdns.log
  level: error
plugins:
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - /var/mosdns/geosite_cn.txt
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - /var/mosdns/geoip_cn.txt
  - tag: geosite_apple
    type: domain_set
    args:
      files:
        - /var/mosdns/geosite_apple.txt
  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - /var/mosdns/geosite_geolocation-!cn.txt
  - tag: whitelist
    type: domain_set
    args:
      files:
        - /etc/mosdns/rule/whitelist.txt
  - tag: blocklist
    type: domain_set
    args:
      files:
        - /etc/mosdns/rule/blocklist.txt
  - tag: greylist
    type: domain_set
    args:
      files:
        - /etc/mosdns/rule/greylist.txt
  - tag: ddnslist
    type: domain_set
    args:
      files:
        - /etc/mosdns/rule/ddnslist.txt
  - tag: hosts
    type: hosts
    args:
      files:
        - /etc/mosdns/rule/hosts.txt
  - tag: redirect
    type: redirect
    args:
      files:
        - /etc/mosdns/rule/redirect.txt
  - tag: adlist
    type: domain_set
    args:
      files:
        - /var/mosdns/disable-ads.txt
  - tag: local_ptr
    type: domain_set
    args:
      files:
        - /etc/mosdns/rule/local-ptr.txt
  - tag: stream_media
    type: domain_set
    args:
      files:
        - /var/mosdns/geosite_disney.txt
        - /var/mosdns/geosite_netflix.txt
        - /var/mosdns/geosite_hulu.txt
        - /etc/mosdns/rule/streaming.txt
  - tag: lazy_cache
    type: cache
    args:
      size: 8000
      lazy_cache_ttl: 86400
  - tag: ali
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: 'https://223.5.5.5/dns-query'
          dial_addr: 223.5.5.5
          idle_timeout: 30
        - addr: 'https://223.6.6.6/dns-query'
          dial_addr: 223.6.6.6
          idle_timeout: 30
        - addr: 'tls://223.5.5.5'
          dial_addr: 223.5.5.5
          idle_timeout: 30
        - addr: 'tls://dns.alidns.com'
          dial_addr: '2400:3200:baba::1'
          idle_timeout: 30
        - addr: 'https://223.5.5.5/dns-query'
          enable_http3: true
          idle_timeout: 30
        - addr: 'https://[2400:3200::1]/dns-query'
          enable_http3: true
          idle_timeout: 30
  - tag: dnspod
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: 'https://1.12.12.12/dns-query'
          dial_addr: 1.12.12.12
          idle_timeout: 30
        - addr: 'https://120.53.53.53/dns-query'
          dial_addr: 120.53.53.53
          idle_timeout: 30
        - addr: 'tls://1.12.12.12'
          dial_addr: 1.12.12.12
          enable_pipeline: true
          idle_timeout: 30
        - addr: 'tls://120.53.53.53'
          dial_addr: 120.53.53.53
          enable_pipeline: true
          idle_timeout: 30
  - tag: google
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::6464"
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::0064"
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::8844"
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::8888"
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.4.4"
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8"

        - addr: "tls://dns.google"
          dial_addr: "8.8.4.4"
          enable_pipeline: true # TCP/DoT 启用 RFC 7766 新的 query pipelining 连接复用模式
        - addr: "tls://dns.google"
          dial_addr: "2001:4860:4860::8888"
          enable_pipeline: true
        - addr: "tls://dns.google"
          dial_addr: "8.8.8.8"
          enable_pipeline: true
        # h3
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::8844"
          enable_http3: true
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.4.4"
          enable_http3: true
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::8888"
          enable_http3: true
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8"
          enable_http3: true
  - tag: cloudflare
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: 'https://1.1.1.1/dns-query'
          dial_addr: 1.1.1.1
          idle_timeout: 30
        - addr: 'https://1.0.0.1/dns-query'
          dial_addr: 1.0.0.1
          idle_timeout: 30
        - addr: 'tls://1.1.1.1'
          dial_addr: 1.1.1.1
          enable_pipeline: true
          idle_timeout: 30
        - addr: 'tls://1.0.0.1'
          dial_addr: 1.0.0.1
          enable_pipeline: true
          idle_timeout: 30
  - tag: upstream_google_ecs
    type: sequence
    args:
      - exec: ecs x.x.x.x
      - exec: $google
  - tag: upstream_cloudflare_ecs
    type: sequence
    args:
      - exec: ecs x.x.x.x
      - exec: $cloudflare
  - tag: forward_local
    type: fallback
    args:
      primary: ali
      secondary: dnspod
      threshold: 200
      always_standby: true
  - tag: forward_remote
    type: fallback
    args:
      primary: upstream_google_ecs
      secondary: upstream_cloudflare_ecs
      threshold: 400
      always_standby: true
  - tag: modify_ttl
    type: sequence
    args:
      - exec: ttl 0-0
  - tag: modify_ddns_ttl
    type: sequence
    args:
      - exec: ttl 5-5
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: qname $ddnslist
        exec: $modify_ddns_ttl
      - matches: '!qname $ddnslist'
        exec: $modify_ttl
      - matches: has_resp
        exec: accept
  - tag: query_is_non_local_ip
    type: sequence
    args:
      - exec: $forward_local
      - matches: '!resp_ip $geoip_cn'
        exec: drop_resp
  - tag: apple_domain_fallback
    type: fallback
    args:
      primary: query_is_non_local_ip
      secondary: forward_local
      threshold: 100
      always_standby: true
  - tag: query_is_apple_domain
    type: sequence
    args:
      - matches: '!qname $geosite_apple'
        exec: return
      - exec: $apple_domain_fallback
  - tag: query_is_ddns_domain
    type: sequence
    args:
      - matches: qname $ddnslist
        exec: $forward_local
  - tag: query_is_local_domain
    type: sequence
    args:
      - matches: qname $geosite_cn
        exec: $forward_local
  - tag: query_is_no_local_domain
    type: sequence
    args:
      - matches: qname $geosite_no_cn
        exec: $forward_remote
  - tag: query_is_whitelist_domain
    type: sequence
    args:
      - matches: qname $whitelist
        exec: $forward_local
  - tag: query_is_greylist_domain
    type: sequence
    args:
      - matches: qname $greylist
        exec: $forward_remote
  - tag: query_is_reject_domain
    type: sequence
    args:
      - matches: qname $blocklist
        exec: reject 3
      - matches: qname $adlist
        exec: reject 3
      - matches:
          - qtype 12
          - qname $local_ptr
        exec: reject 3
      - matches: qtype 65
        exec: reject 3
  - tag: query_is_stream_media_domain
    type: sequence
    args:
      - matches: qname $stream_media
        exec: $forward_remote
  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - exec: jump has_resp_sequence
      - matches:
          - '!qname $ddnslist'
          - '!qname $blocklist'
          - '!qname $adlist'
          - '!qname $local_ptr'
        exec: $lazy_cache
      - exec: $redirect
      - exec: jump has_resp_sequence
      - exec: $query_is_ddns_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_whitelist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_reject_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_greylist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_local_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_no_local_domain
      - exec: jump has_resp_sequence
      - exec: $forward_remote
      - exec: jump has_resp_sequence
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ':5333'
  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ':5333'
